name: Metrics

on:
  # 1. Update automatically every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # 2. Update INSTANTLY every time you push code to main
  push:
    branches: ["main", "master"]
  # 3. Allow manual runs
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MrAghaei
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tehran
